name: CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@master
      - name: make
        run: make
      - uses: actions/upload-artifact@master
        with:
          name: dsvpn
          path: dsvpn
